### ISSUE TITLE
Hi, I need your help

### ISSUE THREAD

**Issue by sunbufu** [StudioPixMix/ANE-InAppPurchase#5]
Hello, first of all thank you for willing to share the spirit, then I want to know that, How to purchase multiple products?

**Comment by MaximePhilipp** [comment]
Hi,
You can't buy multiple products at once, if you want to make a 'bundle' purchase you'll have to create a new inapp purchase for that on your Google and/or iOS dev console.

**Comment by sunbufu** [comment]
Thank you
